---

# Copyright (c) 2020 Robert LaRocca https://www.laroccx.com

# This ansible playbook will update all of the available packages installed on
# a host and reboots the operating system if required. The playbook only works
# with Debian based distributions like Ubuntu and Raspbian.

# Run this playbook using the following command:
# ansible-playbook reboot.yml -i hosts -u root --extra-vars "group=containers"

- hosts: "{{ group }}"
  become: true
  become_user: root
  any_errors_fatal: false
  tasks:
    - name: Check system uptime
      shell: uptime
      register: UPTIME_PRE_REBOOT

    - debug: msg={{UPTIME_PRE_REBOOT.stdout}}

    - name: Reboot operating system
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 10
        reboot_timeout: 1800
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime

    - name: Check system uptime post-reboot
      shell: uptime
      register: UPTIME_POST_REBOOT

    - debug: msg={{UPTIME_POST_REBOOT.stdout}}

